<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZSxjdm7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZSxjdm7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZSxjdm7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZSxjdm7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZSxjdm7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZSxjdm7',
    'container.build_id' => 'a1d4bbc4',
    'container.build_time' => 1573675849,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZSxjdm7');
